services:
  app:
    build: .
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - ./mods:/root/mc/mods
      - ./config:/root/mc/config
      - ./world:/root/mc/world
      - ./server.properties:/root/mc/server.properties
      - ./start.sh:/root/mc/start.sh
      - ./logs:/root/mc/logs
      - ./crash-reports:/root/mc/crash-reports
      - ./WorldBackup:/root/mc/WorldBackup
      - ./luckperms:/root/mc/luckperms
      - ./nucleus:/root/mc/nucleus
      - ./white-list.json:/root/mc/white-list.json
    tty: true
