services:
  server:
    build: .
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - ./mods:/root/mc/mods
      - ./config:/root/mc/config
      - ./world:/root/mc/world
      - ./server.properties:/root/mc/server.properties
